### ISSUE TITLE
Erroneous complaint about lacking HDF5 patch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#108]
```
What steps will reproduce the problem?
1. Start python 2.7.2 on Gentoo Linux
2. Give command "import netCDF4"

What is the expected output? What do you see instead?

Command should be accepted, but I get

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4.pyx", line 821, in init netCDF4 (netCDF4.c:40808)
ImportError: netCDF4 module must be linked against HDF5 version 1.8.4-patch1 or 
higher, got 1.8.4

However, the patched version IS installed on the system.

What version of the product are you using? On what operating system?

netCDF4 0.9.7 on Gentoo Linux



```

Original issue reported on code.google.com by `schicker...@gmail.com` on 3 Feb 2012 at 4:09

**Comment by GoogleCodeExporter** [comment]
```
According to gentoo, 1.8.4-r1 is available, not patch1

http://packages.gentoo.org/package/sci-libs/hdf5

Why not just upgrade to hdf5 1.8.8/netcdf 4.1.3?  There have been lots of bugs 
fixed since 1.8.4-patch1.

```

Original comment by `whitaker.jeffrey@gmail.com` on 3 Feb 2012 at 4:22

**Comment by GoogleCodeExporter** [comment]
```

We thought that !r1 includes patch1, thanks for pointing out that this is
mistaken.[[BR]]
HDF5-1.8.8 is of course an option, but it is not yet stable, so we'd
prefer to find another solution. Any workaround?

```

Original comment by `schicker...@gmail.com` on 4 Feb 2012 at 7:08

**Comment by GoogleCodeExporter** [comment]
```
1.8.8 is quite stable. Versions pre 1.8.4-patch1 have serious bugs.  The only 
other option would be to compile yourself.
```

Original comment by `whitaker.jeffrey@gmail.com` on 4 Feb 2012 at 1:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
