### ISSUE TITLE
ValueError: did not find netCDF version 4 headers /usr/lib/include

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#112]
```
What steps will reproduce the problem?
1. chaoyue@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9$ sudo bash
2. root@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9# export 
NETCDF4_DIR=/usr/lib
3.
root@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9# python setup.py install

HDF5_DIR environment variable not set, checking some standard locations ..
checking /home/chaoyue ...
checking /usr/local ...
HDF5 found in /usr/local
Traceback (most recent call last):
  File "setup.py", line 107, in <module>
    raise ValueError('did not find netCDF version 4 headers %s' % netCDF4_includedir)
ValueError: did not find netCDF version 4 headers /usr/lib/include


What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?

both netCDF4-0.9.8 and netCDF4-0.9.9 show the same error information.

I am working on ubuntu 11.04:

chaoyue@chaoyue-Aspire-4750:~/Downloads$ uname -a
inux chaoyue-Aspire-4750 2.6.38-8-generic #42-Ubuntu SMP Mon Apr 11 03:31:50 
UTC 2011 i686 i686 i386 GNU/Linux


Please provide any additional information below.


I installed the netcdf library from libnetcdf4_3.6.2-2_i386.deb by using 
command:
chaoyue@chaoyue-Aspire-4750:~/Downloads$ sudo dpkg -i 
libnetcdf4_3.6.2-2_i386.deb

chaoyue@chaoyue-Aspire-4750:~/Downloads$ dpkg -l '*netcdf*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version                              
Description
+++-====================================-====================================-==
================================================================================
======
ii  libnetcdf4                           1:3.6.2-2                            
An interface for scientific data access to large binary data
ii  libnetcdf6                           1:4.1.1-5build1                      
An interface for scientific data access to large binary data
ii  netcdf-bin                           1:4.1.1-5build1                      
Programs for reading and writing NetCDF files
ii  netcdf-dbg                           1:4.1.1-5build1                      
debugging symbols for NetCDF


chaoyue@chaoyue-Aspire-4750:~/Downloads$ dpkg -L libnetcdf4
/.
/usr
/usr/lib
/usr/lib/libnetcdff.so.4.0.0
/usr/lib/libnetcdf.so.4.0.0
/usr/lib/libnetcdf_c++.so.4.0.0
/usr/share
/usr/share/doc
/usr/share/doc/libnetcdf4
/usr/share/doc/libnetcdf4/README
/usr/share/doc/libnetcdf4/copyright
/usr/share/doc/libnetcdf4/changelog.gz
/usr/share/doc/libnetcdf4/changelog.Debian.gz
/usr/lib/libnetcdff.so.4
/usr/lib/libnetcdf.so.4
/usr/lib/libnetcdf_c++.so.4

Then I do like:
chaoyue@chaoyue-Aspire-4750:~/Downloads$ cd netCDF4-0.9.9
chaoyue@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9$ sudo bash
root@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9# 
root@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9# export NETCDF4_DIR=/usr/lib
root@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9# python setup.py install

HDF5_DIR environment variable not set, checking some standard locations ..
checking /home/chaoyue ...
checking /usr/local ...
HDF5 found in /usr/local
Traceback (most recent call last):
  File "setup.py", line 106, in <module>
    raise ValueError('did not find netCDF version 4 headers %s' % netCDF4_includedir)
ValueError: did not find netCDF version 4 headers /usr/lib/include
root@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9# echo $NETCDF4_DIR
/usr/lib


**********To display nc config information*********************
chaoyue@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9$ nc-config --all

This netCDF 4.1.1 has been built with the following features: 

  --cc        -> gcc
  --cflags    ->  -I/usr/include
  --libs      -> -L/usr/lib -lnetcdf

  --cxx       -> g++
  --has-c++   -> yes

  --fc        -> gfortran
  --fflags    -> -g -O2 -I/usr/include
  --flibs     -> -L/usr/lib -lnetcdff -lnetcdf
  --has-f77   -> yes
  --has-f90   -> yes

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-szlib -> no

  --prefix    -> /usr
  --includedir-> /usr/include
  --version   -> netCDF 4.1.1




```

Original issue reported on code.google.com by `chaoyue...@gmail.com` on 4 Mar 2012 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
You should either not set NETCDF4_DIR (in which case it will look in /usr/local 
and /usr), or set it to /usr, not /usr/lib.

It could also be that you have no /usr/include/netcdf.h, in which case you 
probably need the netcdf-dev package.
```

Original comment by `whitaker.jeffrey@gmail.com` on 5 Mar 2012 at 5:01

**Comment by GoogleCodeExporter** [comment]
```
Thanks Jeff.

1. I tried the first suggestion, and it gave the same error message.
2. Then I try to list /usr/include/netcdf.h, I found that I don't have 
/usr/include/netcdf.h on my computer. 
Then I download the package libnetcdf-dev_3.6.2-2_i386.deb and install:
chaoyue@chaoyue-Aspire-4750:~/Downloads$ sudo dpkg -i 
libnetcdf-dev_3.6.2-2_i386.deb
[sudo] password for chaoyue: 
Selecting previously deselected package libnetcdf-dev.
(Reading database ... 182814 files and directories currently installed.)
Unpacking libnetcdf-dev (from libnetcdf-dev_3.6.2-2_i386.deb) ...
Setting up libnetcdf-dev (1:3.6.2-2) ...
Processing triggers for man-db ...

chaoyue@chaoyue-Aspire-4750:~/Downloads$ ls /usr/include/netcdf.h
/usr/include/netcdf.h

chaoyue@chaoyue-Aspire-4750:~/Downloads$ cd netCDF4-0.9.9/
chaoyue@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9$ sudo python setup.py 
install

HDF5_DIR environment variable not set, checking some standard locations ..
checking /home/chaoyue ...
checking /usr/local ...
HDF5 found in /usr/local

NETCDF4_DIR environment variable not set, checking standard locations.. 
checking /home/chaoyue ...
checking /usr/local ...
checking /sw ...
checking /opt ...
checking /opt/local ...
checking /usr ...
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    raise ValueError('did not find netCDF version 4 headers')
ValueError: did not find netCDF version 4 headers

chaoyue@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9$ nc-config --all

This netCDF 4.1.1 has been built with the following features: 

  --cc        -> gcc
  --cflags    ->  -I/usr/include
  --libs      -> -L/usr/lib -lnetcdf

  --cxx       -> g++
  --has-c++   -> yes

  --fc        -> gfortran
  --fflags    -> -g -O2 -I/usr/include
  --flibs     -> -L/usr/lib -lnetcdff -lnetcdf
  --has-f77   -> yes
  --has-f90   -> yes

  --has-dap   -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-szlib -> no

  --prefix    -> /usr
  --includedir-> /usr/include
  --version   -> netCDF 4.1.1

chaoyue@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9$ dpkg -l '*netcdf*'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version                              
Description
+++-====================================-====================================-==
================================================================================
======
ii  libnetcdf-dev                        1:3.6.2-2                            
Development kit for NetCDF
ii  libnetcdf4                           1:3.6.2-2                            
An interface for scientific data access to large binary data
ii  libnetcdf6                           1:4.1.1-5build1                      
An interface for scientific data access to large binary data
ii  netcdf-bin                           1:4.1.1-5build1                      
Programs for reading and writing NetCDF files
ii  netcdf-dbg                           1:4.1.1-5build1                      
debugging symbols for NetCDF
un  netcdf-dev                           <none>                               
(no description available)
un  netcdf-doc                           <none>                               
(no description available)
un  netcdfg-dev                          <none>                               
(no description available)


chaoyue@chaoyue-Aspire-4750:~/Downloads/netCDF4-0.9.9$ dpkg -L libnetcdf-dev
/.
/usr
/usr/lib
/usr/lib/libnetcdff.a
/usr/lib/libnetcdf.a
/usr/lib/libnetcdf_c++.a
/usr/include
/usr/include/ncvalues.h
/usr/include/netcdf.h
/usr/include/netcdf.hh
/usr/include/netcdf.inc
/usr/include/netcdf.mod
/usr/include/netcdfcpp.h
/usr/include/typesizes.mod
/usr/share
/usr/share/man
/usr/share/man/man3
/usr/share/man/man3/netcdf_f90.3f90.gz
/usr/share/man/man3/netcdf.3.gz
/usr/share/man/man3/netcdf_f77.3.gz
/usr/share/doc
/usr/share/doc/libnetcdf-dev
/usr/share/doc/libnetcdf-dev/copyright
/usr/lib/libnetcdff.so
/usr/lib/libnetcdf.so
/usr/lib/libnetcdf_c++.so
/usr/share/doc/libnetcdf-dev/README
/usr/share/doc/libnetcdf-dev/changelog.gz
/usr/share/doc/libnetcdf-dev/changelog.Debian.gz

Could you please check it for me? Thanks very much!

-Chao



```

Original comment by `chaoyue...@gmail.com` on 5 Mar 2012 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
Note the version on libnetcdf-dev (3.6.2).  You need 4.1.1.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 7 Mar 2012 at 4:01

**Comment by GoogleCodeExporter** [comment]
```
it's working now. thanks a lot!!

-Chao
```

Original comment by `chaoyue...@gmail.com` on 7 Mar 2012 at 9:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
