### ISSUE TITLE
Report accessing closed file error instead of Not a valid ID error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#116]
```
What steps will reproduce the problem?
>>> from netCDF4 import Dataset
>>> d = Dataset('test.nc', 'w')
>>> d.createDimension('x', 10)
>>> len(d.dimensions['x'])
>>> d.close()
>>> len(d.dimensions['x'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4.pyx", line 1864, in netCDF4.Dimension.__len__ (netCDF4.c:19769)
RuntimeError: NetCDF: Not a valid ID

What is the expected output? What do you see instead?
Some error stating I'm trying to access variables on a closed file
An ID error

What version of the product are you using? On what operating system?
0.9.9, Fedora 16

Please provide any additional information below.
Obviously not critical, but it potentially clears up confusion.

```

Original issue reported on code.google.com by `childs...@gmail.com` on 5 Apr 2012 at 2:36

**Comment by GoogleCodeExporter** [comment]
```
that error message is coming from the C library -  not much I can do about it.
```

Original comment by `whitaker.jeffrey@gmail.com` on 5 Apr 2012 at 2:42

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
