### ISSUE TITLE
Unable to read/write attributes that are arrays of strings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#118]
```
NetCDF 4 supports attributes that are Arrays of Strings.  netcdf4-python seems 
not to support this.

To demonstrate, I can take the example code from section "6.31.2 Reading and 
Writing Arrays of Strings" of "The NetCDF C Interface Guide", version 4.1.3.  
This creates a netCDF4 file that we can examine as follows:

$ ncdump test.nc 
netcdf test {

// global attributes:
        string :MyAttribute = "Let but your honour know", "Whom I believe to be most strait in virtue", "That, in the working of your own affections", "Had time cohered with place or place with wishing", "Or that the resolute acting of your blood", "Could have attain’d the effect of your own purpose", "Whether you had not sometime in your life", "Err’d in this point which now you censure him", "And pull’d the law upon you." ;
}

(To easily create this test.nc file without writing any code, copy the above 
output into a file "test.cdl" and then run "ncgen -b test.cdl".)

Trying to read this file with netcdf4-python results in errors:

$ python
Python 2.7.2 (v2.7.2:8527427914a2, Jun 11 2011, 15:22:34) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
>>> print netCDF4.__version__
0.9.9
>>> rootGroup = netCDF4.Dataset('test.nc','r')
>>> print rootGroup.__dict__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4.pyx", line 1715, in netCDF4.Dataset.__getattr__ (netCDF4.c:18057)
  File "netCDF4.pyx", line 901, in netCDF4._get_att (netCDF4.c:10627)
AttributeError: NetCDF: Attempt to convert between text & numbers


Trying to create an attribute which is an Array of Strings results in a single 
string all mashed together:

>>> rootGroup = netCDF4.Dataset('test2.nc','w')
>>> rootGroup.MyAttribute = array(['red','green','blue'])
>>> print rootGroup.MyAttribute
redgreenblue



```

Original issue reported on code.google.com by `eric.nod...@gmail.com` on 12 Apr 2012 at 5:04

**Comment by GoogleCodeExporter** [comment]
```
You can create variables that are variable-length string arrays (see section 10 
in the docs at 
http://netcdf4-python.googlecode.com/svn/trunk/docs/netCDF4-module.html), but 
not attributes.  This will be non-trivial to support, so unless there is a 
compelling use-case it won't be a high priority.

BTW:  I was not able to create the test file (ncgen -b just created an empty 
file), so could you attach your test.nc?  I want to at least make sure it fails 
more gracefully.
```

Original comment by `whitaker.jeffrey@gmail.com` on 12 Apr 2012 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
Here is the test.nc file .

You're quite right, the ncgen command I gave gives an empty file.  Sorry about 
that.  The correct ncgen command is:

 ncgen -b -k 'hdf5' test.cdl

The application is a finite element solver.  The parameter specifies which 
constraints are to be applied to a given problem.  For example:

 Constraints = 'BoundaryCondition1', 'BoundaryCondition2', 'PinThatNode'

The constraints themselves are looked up by name elsewhere in the file (and 
typically each one applies to a whole array of nodes/elements, so that 
"Constraints" typically only needs to store a couple of strings, as shown).  
We're still in the process of defining our netCDF file layout, so we may just 
decide to switch to using a variable instead of a attribute for this value, 
although the attribute seems like a more natural fit.

```

Original comment by `eric.nod...@gmail.com` on 12 Apr 2012 at 5:59

Attachments:
- [test.nc](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-118/comment-2/test.nc)

**Comment by GoogleCodeExporter** [comment]
```
You could do something like this

from netCDF4 import Dataset
f = Dataset('test.nc','w')
f.Constraints = "BoundaryCondition1; BoundaryCondition2"
f.close()
f = Dataset('test.nc')
constraints = f.Constraints.split(";")
print constraints
f.close()

which gives

[u'BoundaryCondition1', u' BoundaryCondition2']


Should work as long as the constraints are guaranteed not to have a semicolon 
in them.

BTW:  I updated svn so vlen string attributes are silently skipped when opening 
a file, just like other unsupported attribute types.
```

Original comment by `whitaker.jeffrey@gmail.com` on 12 Apr 2012 at 6:35

**Comment by GoogleCodeExporter** [comment]
```
probably a more elegant solution would be to use the json module to serialize 
python objects as strings:

from netCDF4 import Dataset
import json
f = Dataset('test.nc','w')
f.Constraints = json.dumps(["BoundaryCondition1","BoundaryCondition2"])
f.close()
f = Dataset('test.nc')
constraints = json.loads(f.Constraints)
print constraints

this way you could create sting attributes that are easily converted to python 
lists, dicts, tuples etc and yet are still easily readable in ncdump.
```

Original comment by `whitaker.jeffrey@gmail.com` on 12 Apr 2012 at 6:51

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your responses!

If anything, we'd go with something like the semi-colon delimited list.  The 
files need to be (easily) readable and writeable from C and Fortran as well as 
Python.  Actually Fortran is somewhat awkward (when isn't it?), because the 
netCDF-4 Fortran interface doesn't support arrays of strings at all.  However 
we have Fortran-wrapped C routines that do that when required.

```

Original comment by `eric.nod...@gmail.com` on 12 Apr 2012 at 7:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
