### ISSUE TITLE
nc4tonc3 chokes on least_significant_digit attribute

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#15]
```
I just needed an utility to convert netcdf4 to netcdf3 and noticed you
added it a couple of days ago !

I tried it and noticed it got 

Traceback (most recent call last):
  File "/usr/local/bin/nc4tonc3", line 114, in <module>
    nc3tonc4(filename4,filename3,clobber=overwritefile,quiet=quiet)
  File "/usr/local/bin/nc4tonc3", line 37, in nc3tonc4
    setattr(var,attname,getattr(ncvar,attname))
  File "netCDF4.pyx", line 1804, in netCDF4.Variable.__setattr__
(netCDF4.c:12598)
  File "netCDF4.pyx", line 714, in netCDF4._set_att (netCDF4.c:3020)
AttributeError: NetCDF: Not a valid data type or _FillValue type mismatch

So I added those lines to nc4tonc3.py the script see  what happened

        for attname in ncvar.ncattrs():
            try:            
                setattr(var,attname,getattr(ncvar,attname))
            except:
                print 'Could not set attribute', attname, ':',
getattr(ncvar, attname)


and I got 

huardda@angus:~/forcing/wind/80$ nc4tonc3 geowinds.nc geowinds.nc3 
copying global attributes ..
copying dimensions ..
copying variable lat
copying variable uwnd
Could not set attribute least_significant_digit : 6

The uwnd variable is created using

That is, my netcdf variable is generated with

uwnd = root.createVariable('uwnd','f4',('time','y','x',),
zlib=True,least_significant_digit=6)

If you can't guess what the problem is right away, I'll hunt it later on. 
```

Original issue reported on code.google.com by `david.huard` on 6 Apr 2009 at 2:15

**Comment by GoogleCodeExporter** [comment]
```
David:  I just tried it on a file containing a variable with a
least_significant_digit attribute, and did not see that error.   If you post 
the file
for me, I can investigate further.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 6 Apr 2009 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
The file is 2Gb... I'll have a go at finding the bug. 
```

Original comment by `david.huard` on 6 Apr 2009 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
Okay, I'm on a 64 bits machine, so the dtype of the least_siginificant_digit is
int64. In the function _set_att, the code checks that the type is in 
_supportedtypes.
Since it is, there is no need to convert the int64 to int32.  Now, int64 are
supported in netCDF4 but not in netCDF3, right ? So the conversion does not take
place when it should. 

One solution is to open ncfile3 using netCDF3.Dataset, instead of 
netCDF4.Dataset,
but I'll let you judge what's the best approach. 
```

Original comment by `david.huard` on 6 Apr 2009 at 4:44

**Comment by GoogleCodeExporter** [comment]
```
    # if array is 64 bit integers, cast to 32 bit integers
    # if 64-bit datatype not supported.
    if value_arr.dtype.str[1:] == 'i8' and _get_format(grpid)[:7]=='NETCDF3':
        value_arr = value_arr.astype('i4')

Is another, simpler, option.

```

Original comment by `david.huard` on 6 Apr 2009 at 4:58

**Comment by GoogleCodeExporter** [comment]
```
Just committed that, can you try it out and let me know?
```

Original comment by `whitaker.jeffrey@gmail.com` on 6 Apr 2009 at 7:50

**Comment by GoogleCodeExporter** [comment]
```
Looks good. 
```

Original comment by `david.huard` on 6 Apr 2009 at 8:57

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 25 May 2009 at 12:58
- Changed state: **Verified**
