### ISSUE TITLE
HDF error when appending to file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#152]
```
What steps will reproduce the problem?
1. Run the attached file

What is the expected output? What do you see instead?
Expected script to complete. Got error instead:
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    genvar[:] = np.zeros(len(root.dimensions['gens']))
  File "netCDF4.pyx", line 2856, in netCDF4.Variable.__setitem__ (netCDF4.c:32499)
  File "netCDF4.pyx", line 2987, in netCDF4.Variable._put (netCDF4.c:33503)
RuntimeError: NetCDF: HDF error

What version of the product are you using? On what operating system?
Fedora 17
hdf5.i686 1.8.8-8.fc17
netcdf4-python.x86_64 1.0-2.fix1.fc17

Please provide any additional information below.
I suspect there are several things going on here, but I can't figure out what 
they could be. I've stripped out as much as possible but left the order intact 
to try get just the lines that cause the error.
Commenting out lines 11 and 13 will make it work again.
Switching lines 13 and 14 will also make it work.

```

Original issue reported on code.google.com by `childs...@gmail.com` on 17 Dec 2012 at 1:59

Attachments:
- [test.py](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-152/comment-0/test.py)

**Comment by GoogleCodeExporter** [comment]
```
Perhaps related to issue 80, but it doesn't appear to be fixed despite the last 
post.
```

Original comment by `childs...@gmail.com` on 17 Dec 2012 at 2:00

**Comment by GoogleCodeExporter** [comment]
```
This looks a bug in the netcdf library, probably related to the one described 
in issue 80.  We will need to create a simple C program that triggers it (it's 
probably a small modification to the C program included in issue 80) and send 
it to unidata.
```

Original comment by `josh.n.w...@gmail.com` on 24 Dec 2012 at 4:24

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
