### ISSUE TITLE
Dataset.renameVariable method doesn't appear to work properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#17]
```
What steps will reproduce the problem?
1. root = Dataset('a netcdf file', 'r+')
2. root.renameVariable('old name', 'new name')
3.

What is the expected output? What do you see instead?
I expected the statement in (2) to rename the variable in the netcdf file.
Instead I get an error:

Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "netCDF4.pyx", line 1172, in netCDF4.Dataset.renameVariable
(netCDF4.c:5213)
RuntimeError: NetCDF4: Operation not allowed in data mode

What version of the product are you using? On what operating system?
I'm using version 0.8 of the product on a Mac OS X 10.4.11 operating system.

Please provide any additional information below.

I made sure the netcdf file I was opening had its permission settings set
to read/write. I also tried using the 'a' flag instead of the 'r+' flag to
open the data file.
```

Original issue reported on code.google.com by `Michael.Cayanan@gmail.com` on 18 May 2009 at 4:34

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I am actually using version 0.7.7 of the product.
```

Original comment by `Michael.Cayanan@gmail.com` on 18 May 2009 at 6:49

**Comment by GoogleCodeExporter** [comment]
```
I was able to reproduce your error with this script:

import netCDF4
f  = netCDF4.Dataset('test.nc', 'w, format='NETCDF3_64BIT'')
f.createDimension('time',None)
f.createVariable('SurfPres_A','f4', 'time')
f.close()
f  = netCDF4.Dataset('test.nc', 'r+')
f.renameVariable('SurfPres_A','surface_air_pressure')
f.close()

The error does not occur if the format is NETCDF4 or NETCDF4_CLASSIC.  I will 
let you know when I have a fix.

It may be a bug in the library (the dependence of string length looks 
suspicious).  If so, I will file a bug report 
with Unidata and cc you.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 18 May 2009 at 7:25

**Comment by GoogleCodeExporter** [comment]
```
Thanks Jeff. The format for the netcdf file I'm modifying is NETCDF3_CLASSIC. 
I'm
wondering if you can reproduce the error under this format as well.
```

Original comment by `Michael.Cayanan@gmail.com` on 18 May 2009 at 7:37

**Comment by GoogleCodeExporter** [comment]
```
It is a library bug.  I filed a bug report with unidata, along with a simple C
program that reproduces it.  I'll update this ticket when I hear from them.
```

Original comment by `whitaker.jeffrey@gmail.com` on 21 May 2009 at 1:36

**Comment by GoogleCodeExporter** [comment]
```
This should be fixed now in SVN.  Can you verify?

(the workaround was to wrap nc_redef and nc_endef calls around the rename_var 
call)

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 21 May 2009 at 4:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 25 May 2009 at 12:57
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hi Jeff. I checked out the latest code in SVN, installed it on my system and 
re-ran
the test case and unfortunately, I am still seeing the same error:

>>> import netCDF4
>>> root = netCDF4.Dataset('/Users/mcayanan/temp/hdfeos-netcdf_fix/output.nc', 
'r+')
>>> root.renameVariable('ascending_SurfPres_A', 
'ascending_surface_air_pressure')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4.pyx", line 1386, in netCDF4.Dataset.renameVariable (netCDF4.c:6351)
RuntimeError: NetCDF: Operation not allowed in data mode
>>> root.file_format
'NETCDF3_CLASSIC'
>>> 
```

Original comment by `Michael.Cayanan@gmail.com` on 26 May 2009 at 7:38

**Comment by GoogleCodeExporter** [comment]
```
Michael:  It turns out I forgot to commit the updated C source file (only the 
.pyx
file was updated in SVN).  Try it now.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 26 May 2009 at 7:59

**Comment by GoogleCodeExporter** [comment]
```
Hi Jeff. That worked. I was able to rename the variable successfully. Thanks 
again
for helping me fix this!
```

Original comment by `Michael.Cayanan@gmail.com` on 26 May 2009 at 8:06
