### ISSUE TITLE
RuntimeError: NetCDF: Operation not allowed in define mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#193]
```
What steps will reproduce the problem?
1. run the attached python script to see the exception (the exception also 
occurs when format='NETCDF3_64BIT')
2. Change(decrease) to 1000 the number of times stored in the netcdf file and 
the error will not occur.
3. with 10000 steps and format of the netcdf file 'NETCDF4_CLASSIC' the program 
works correctly

What is the expected output? What do you see instead?
Expect program to run without the exception.
Instead I see the following exception:

Traceback (most recent call last):
  File "test_nc4.py", line 29, in <module>
    latVariable[:] = lat2d
  File "netCDF4.pyx", line 2884, in netCDF4.Variable.__setitem__ (netCDF4.c:36319)
  File "netCDF4.pyx", line 3013, in netCDF4.Variable._put (netCDF4.c:37295)
RuntimeError: NetCDF: Operation not allowed in define mode


What version of the product are you using? On what operating system?
netCDF4=1.0.4
Cython==0.19.1
numpy==1.7.1

Python 2.7.2 (default, Mar  6 2012, 20:05:29)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-48)] on linux2

Please provide any additional information below.
I work under virtualenv(1.9.1).



```

Original issue reported on code.google.com by `guziy.sa...@gmail.com` on 9 Aug 2013 at 4:00

Attachments:
- [test_nc4.py](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-193/comment-0/test_nc4.py)

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
