### ISSUE TITLE
HDF error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#210]
```
What steps will reproduce the problem?
1. Run attached file
2.
3.

What is the expected output? What do you see instead?
Traceback (most recent call last):
  File "testa_nc.py", line 18, in <module>
    tempo = fu.variables['time'][:,:]
  File "netCDF4.pyx", line 2778, in netCDF4.Variable.__getitem__ (netCDF4.c:34463)
  File "netCDF4.pyx", line 3312, in netCDF4.Variable._get (netCDF4.c:40968)
RuntimeError: NetCDF: HDF error

I would like to create some matrix with variables from netCDF file

What version of the product are you using? On what operating system?
Python 2.7.6 :: Anaconda 1.8.0 (32-bit)
HDF5 1.8.9
netCDF4 1.0.6
ubuntu 12.04 32-bit

Please provide any additional information below.

```

Original issue reported on code.google.com by `adrienid...@gmail.com` on 6 Dec 2013 at 6:41

Attachments:
- [testa_nc.py](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-210/comment-0/testa_nc.py)

**Comment by GoogleCodeExporter** [comment]
```
Can't run that script without the data file.  Please upload the data.
```

Original comment by `whitaker.jeffrey@gmail.com` on 6 Dec 2013 at 7:46

**Comment by GoogleCodeExporter** [comment]
```
I'm sorry. I forget to attach the file.
```

Original comment by `adrienid...@gmail.com` on 7 Dec 2013 at 11:59

Attachments:
- [IFR_L2_WNF_19920312_005524_19920312_023440_03425.nc](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-210/comment-2/IFR_L2_WNF_19920312_005524_19920312_023440_03425.nc)

**Comment by GoogleCodeExporter** [comment]
```
Works for me. I suspect this was a bug that was fixed in either the HDF5 or 
netcdf C libraries.  Try upgrading one or both.
```

Original comment by `whitaker.jeffrey@gmail.com` on 8 Dec 2013 at 1:10

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
