### ISSUE TITLE
[request] win32-py2.6 binary release

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#27]
```
Please make a python 2.6 build for win32, it would be a great help - I 
don't have the time to build it myself but I should install netCDF on 
many workstations with activepython 2.6...
```

Original issue reported on code.google.com by `csi...@gmail.com` on 24 Oct 2009 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
I don't have access to a Windows machine to make binary releases for that 
platform. 
The binary 2.5 releases on the download page were contributed by a user, and he 
is
not ready to install 2.6 yet.  

So, the bottom line is that there will be no Python26 windows binary installer 
until
someone steps up to contribute one.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 26 Oct 2009 at 10:01

**Comment by GoogleCodeExporter** [comment]
```
I can do this. Not now, but I'll try to get that done by next week. 
```

Original comment by `david.huard` on 28 Jan 2010 at 4:05

**Comment by GoogleCodeExporter** [comment]
```
That will be really helpful. Even I am looking for a python 2.6 compatible 
binary. 
Thanks!
```

Original comment by `sadhan.s...@gmail.com` on 7 Feb 2010 at 10:20

**Comment by GoogleCodeExporter** [comment]
```
There are unofficial binaries at 
<http://www.lfd.uci.edu/~gohlke/pythonlibs/#netcdf4>
if you don't mind trying. They were compiled against netcdf 4.1 and numpy 1.4.0.
Unfortunately, they crash during the tst_compound*.py tests.
```

Original comment by `cjgoh...@gmail.com` on 8 Feb 2010 at 12:43

**Comment by GoogleCodeExporter** [comment]
```
Christoph:  Thanks for making those available.  Did you build against HDF 
1.8.4?  If not, 
that would explain the crash on tst_compound*py.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 8 Feb 2010 at 12:56

**Comment by GoogleCodeExporter** [comment]
```
I have compiled netcdf4-python 0.9 (svn), netcdf 4.1 (final), hdf5 1.8.4 
(final), and
numpy 1.4.0 from sources using msvc9. The 32 bit netcdf and hdf5 binaries pass 
all
selftests. When using the netcdf 4.1-rc1 DLL with netcdf4-python 0.9, the 
compound
tests pass and do not crash. 

Is netcdf4-python 0.9 confirmed to work with netcdf 4.1 (final) on other 
platforms? 

Btw, the Win32/MSVC projects were pulled from netcdf 4.1 (final) on the day it 
was
released... 
```

Original comment by `cjgoh...@gmail.com` on 8 Feb 2010 at 11:53

**Comment by GoogleCodeExporter** [comment]
```
I've verified svn head passes all tests on macos x and linux x86_64.  I
```

Original comment by `whitaker.jeffrey@gmail.com` on 9 Feb 2010 at 12:12

**Comment by GoogleCodeExporter** [comment]
```
Thanks! Turned out the netcdf 4.1 dll was built with the /MT switch instead of 
/MD. 

Only one serious test failure remains:

======================================================================
ERROR: testing variable slicing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_slicing.py", line 17, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4.pyx", line 1291, in netCDF4.Dataset.__init__ (netCDF4.c:5752)
RuntimeError: Can't add HDF5 file metadata

----------------------------------------------------------------------
```

Original comment by `cjgoh...@gmail.com` on 9 Feb 2010 at 1:19

**Comment by GoogleCodeExporter** [comment]
```
No idea what's causing that one.  It's dying trying to create the file.  I 
wonder if it's a 
filesystem issue.  Is it repeatable (does it always fail on the same test in 
the same place?
).
```

Original comment by `whitaker.jeffrey@gmail.com` on 9 Feb 2010 at 3:13

**Comment by GoogleCodeExporter** [comment]
```
OK. There are some other failures of this type that I have also seen in other 
package
tests:

WindowsError: [Error 32] The process cannot access the file because it is being 
used
by another process: ...


A 32 bit Windows installer for Python 2.6 is attached. It was compiled against 
numpy
1.3 (1.4 was pulled today) and is missing opendap support.


```

Original comment by `cjgoh...@gmail.com` on 9 Feb 2010 at 4:23

Attachments:
- [netCDF4-0.9.win32-py2.6.exe](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-27/comment-10/netCDF4-0.9.win32-py2.6.exe)

**Comment by GoogleCodeExporter** [comment]
```
Thanks!  Just curious - how hard would it be to get dap support working on 
windows?

```

Original comment by `whitaker.jeffrey@gmail.com` on 9 Feb 2010 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
I guess not too hard. If I understood correctly, the libncdap source is now 
included
in the netCDF 4.1 release and the only external requirement is libcurl, which is
trivial. Can you confirm this? 
However 1) the configure script does not run in a Win32 environment, 2) 
libncdap was
not included in the MSVC solution provided in rc1, and 3) support for building 
netcdf
on Windows does not seem to exist.
When I find the time I will try configure netcdf in cygwin with DAP support and 
build
my own VC project files for libncdap from the configure output.
```

Original comment by `cjgoh...@gmail.com` on 9 Feb 2010 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
Yes, it is true that libcurl is the only external requirement.

It sounds like it may be quite a bit of work though.  Thanks for letting me 
know.  I'll 
post your non-dap windows exe on the download site.
```

Original comment by `whitaker.jeffrey@gmail.com` on 9 Feb 2010 at 10:56

**Comment by GoogleCodeExporter** [comment]
```
Christoph/David:  If either of you has time to build a new windows installer 
for version 0.9.1, built against hdf5 
1.8.4-patch1 and netcdf-4.1.1, I would be very grateful.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 8 Apr 2010 at 7:05

**Comment by GoogleCodeExporter** [comment]
```
I just built new binaries against hdf5 1.8.4-patch1, netcdf-4.1.1 (without 
DAP), and
numpy 1.4.1rc1: http://www.lfd.uci.edu/~gohlke/pythonlibs/#netcdf4. These are 
msvc9
builds. Feel free to test and redistribute the files.

Netcdf-4.1.1 comes without Visual Studio projects. I used the project files from
4.1rc, which still seem to produce working libraries after some small changes.

Test/run_all.py fails the same tests on 32 and 64 bit, mostly due to file 
access issues:

...EE...........E....EHDF5-DIAG: Error detected in HDF5 (1.8.4-patch1) thread 0:
  #000: ..\..\..\src\H5F.c line 1432 in H5Fcreate(): unable to create file
    major: File accessability
    minor: Unable to open file
  #001: ..\..\..\src\H5F.c line 1239 in H5F_open(): unable to truncate a file which
is already open
    major: File accessability
    minor: Unable to open file
E................
======================================================================
ERROR: testing zlib and shuffle compression filters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_compression.py", line 41, in tearDown
    os.remove(file)
WindowsError: [Error 32] The process cannot access the file because it is being 
used
by another proc
ess: 'c:\\users\\gohlke\\appdata\\local\\temp\\tmpn8mumn.nc'

======================================================================
ERROR: testing access of data over http using opendap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_dap.py", line 28, in runTest
    file = netCDF4.Dataset(URL)
  File "netCDF4.pyx", line 1326, in netCDF4.Dataset.__init__ (netCDF4.c:5854)
RuntimeError: Invalid argument

======================================================================
ERROR: test_select_nc (tst_netcdftime.TestDate2index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_netcdftime.py", line 221, in tearDown
    os.remove(self.file)
WindowsError: [Error 32] The process cannot access the file because it is being 
used
by another proc
ess: 'c:\\users\\gohlke\\appdata\\local\\temp\\tmpa26cwj.nc'

======================================================================
ERROR: test_1d (tst_slicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_slicing.py", line 39, in tearDown
    os.remove(self.file)
WindowsError: [Error 32] The process cannot access the file because it is being 
used
by another proc
ess: 'c:\\users\\gohlke\\appdata\\local\\temp\\tmpkmkkpy.nc'

======================================================================
ERROR: testing variable slicing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_slicing.py", line 17, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4.pyx", line 1326, in netCDF4.Dataset.__init__ (netCDF4.c:5854)
RuntimeError: Can't add HDF5 file metadata

----------------------------------------------------------------------
Ran 39 tests in 1.005s

FAILED (errors=5)
```

Original comment by `cjgoh...@gmail.com` on 8 Apr 2010 at 7:46

**Comment by GoogleCodeExporter** [comment]
```
Christoph:  That's great - thanks!  David - could you test on windows and see 
if you get those some file access 
errors?

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 9 Apr 2010 at 2:34

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
