### ISSUE TITLE
netCDF4.c(230) : error C2026: string too big, trailing characters truncated

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#29]
```
When building netCDF4-python, version 0.9 from svn, with Microsoft Visual
Studio 2008, the compiler throws error C2026 at line 230 of netCDF4.c.
After breaking up the string into smaller ones as follows, the build succeeds: 

static char __pyx_mdoc[] = "\n"
"Introduction\n"
"============\n"
"\n"

...

"OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR\n"
"PERFORMANCE OF THIS SOFTWARE.";


32- and 64-bit binaries for Python 2.6 for Windows are available at
<http://www.lfd.uci.edu/~gohlke/pythonlibs/#netcdf4>

Christoph
```

Original issue reported on code.google.com by `cjgoh...@gmail.com` on 22 Nov 2009 at 12:31

**Comment by GoogleCodeExporter** [comment]
```
Thanks Christoph!

What versions of HDF5 and netcdf-4 did you link to?


```

Original comment by `whitaker.jeffrey@gmail.com` on 22 Nov 2009 at 12:35

**Comment by GoogleCodeExporter** [comment]
```
I am using HDF5 1.8.4 and netCDF 4.1-rc1, compiled from sources using Visual 
Studio 2008.

Just noticed that netCDF4-python 0.9svn fails the run_all.py tests with the 
following
error. Version 0.8.2 passes most tests.

Traceback (most recent call last):
  File "run_all.py", line 17, in <module>
    m = __import__(os.path.splitext(f)[0])
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_atts.py", line 8, in <module>

    import netCDF4
  File "netCDF4.pyx", line 793, in netCDF4 (netCDF4.c:32198)
ImportError: No module named _ordereddict

Christoph
```

Original comment by `cjgoh...@gmail.com` on 22 Nov 2009 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
The compilation of ordereddict.c must have failed.  Could you try compiling 
again and
see what the error was?


```

Original comment by `whitaker.jeffrey@gmail.com` on 22 Nov 2009 at 12:51

**Comment by GoogleCodeExporter** [comment]
```
Thanks. You were right. It works now, after reloading setup.py from svn. 

Test/run_all.py returns the following 5 errors in both 32- and 64-bit versions. 
In
bench_compress.py writing seems slow (I don't have anything to compare to):

D:\Dev\Compile\NetCDF\netcdf4-svn\test>python26-x64 run_all.py
...EE...........E....EE................
======================================================================
ERROR: testing zlib and shuffle compression filters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_compression.py", line 41, in
tearDown
    os.remove(file)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\\users\\gohlke\\appdata\\local\\temp\\tmp5r0ztl.nc'


======================================================================
ERROR: testing access of data over http using opendap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_dap.py", line 28, in runTest
    file = netCDF4.Dataset(URL)
  File "netCDF4.pyx", line 1289, in netCDF4.Dataset.__init__ (netCDF4.c:6640)
RuntimeError: Invalid argument

======================================================================
ERROR: test_select_nc (tst_netcdftime.TestDate2index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_netcdftime.py", line 214, in
tearDown
    os.remove(self.file)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\\users\\gohlke\\appdata\\local\\temp\\tmprz0vdd.nc'


======================================================================
ERROR: test_1d (tst_slicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_slicing.py", line 39, in tear
Down
    os.remove(self.file)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'c:\\users\\gohlke\\appdata\\local\\temp\\tmprftlmv.nc'


======================================================================
ERROR: testing variable slicing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Dev\Compile\NetCDF\netcdf4-svn\test\tst_slicing.py", line 17, in setU
p
    f = Dataset(file_name,'w')
  File "netCDF4.pyx", line 1289, in netCDF4.Dataset.__init__ (netCDF4.c:6640)
RuntimeError: Can't add HDF5 file metadata

----------------------------------------------------------------------
Ran 39 tests in 0.839s

FAILED (errors=5)


D:\Dev\Compile\NetCDF\netcdf4-svn\examples>python bench_compress.py
reading and writing a 30 by 15 by 73 by 144 random array ..
(average of 10 trials)
testing compression ... zlib=False,shuffle=False
writing took 0.329739393199 seconds
reading took 0.0708450962895 seconds
size of test.nc =  37849750
testing compression ... zlib=True,shuffle=False
writing took 9.04099844541 seconds
reading took 0.632003957132 seconds
size of test.nc =  12816711
testing compression ... zlib=True,shuffle=True
writing took 3.21693664287 seconds
reading took 0.6279646234 seconds
size of test.nc =  9085764
```

Original comment by `cjgoh...@gmail.com` on 22 Nov 2009 at 1:25

**Comment by GoogleCodeExporter** [comment]
```
The slow write performance in bench_compress.py was due to an unoptimized 
zlib1.dll.

```

Original comment by `cjgoh...@gmail.com` on 22 Nov 2009 at 7:11

**Comment by GoogleCodeExporter** [comment]
```
Christoph - seems like there are three errors here.  I don't know what could be
causing the file lock error, but I suspect it's a windows thing.  The DAP error
indicates you didn't compile with --enable-dap - is that correct?  The HDF5 
error in
tst_slicing is the most troubling.  Did you link against HDF5 1.8.4 and 
netcdf-4.1-rc1?
```

Original comment by `whitaker.jeffrey@gmail.com` on 22 Nov 2009 at 1:27

**Comment by GoogleCodeExporter** [comment]
```
The Visual Studio solution/project provided with netCDF 4.1 does not have DAP 
enabled
(there is no configure script in the MS toolchain). Manually enabling USE_DAP 
and
trying to adjust the project files failed so far.

I linked against HDF5 1.8.4 and netcdf-4.1-rc1, compiled from sources using 
project
default settings. Using the HDF5 binaries/libraries provided by the HDF group 
makes
no difference.
```

Original comment by `cjgoh...@gmail.com` on 22 Nov 2009 at 7:53

**Comment by GoogleCodeExporter** [comment]
```
Christoph:  OK, looks as though that's as good as it's going to get on Windows. 
Thanks - I will post the installers on the google code site.  4.1 final should 
be
released in a week or so, would you mind rebuilding them then?

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 22 Nov 2009 at 8:45

**Comment by GoogleCodeExporter** [comment]
```
Sure, I will rebuild when 4.1 final is released and send the installers to you.
netCDF 4.1 RC1 seems to have some problems with the VS2008 build: I get test 
failures
in nc_open and a crash in ncsync. Maybe I contact the netCDF group. Thanks for 
your help!
```

Original comment by `cjgoh...@gmail.com` on 22 Nov 2009 at 8:57

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
