### ISSUE TITLE
HDF error on close when using _FillValue attributes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#54]
```
What steps will reproduce the problem?
1. Run the attached file
2.
3.

What is the expected output? What do you see instead?

I expect a file containing all defined attributes, I get an error instead (and 
a half complete file)

$ python testcase.py 
Traceback (most recent call last):
  File "testcase.py", line 23, in <module>
    rootgrp.close()
  File "netCDF4.pyx", line 1350, in netCDF4.Dataset.close (netCDF4.c:6119)
RuntimeError: HDF error

What version of the product are you using? On what operating system?

netcdf4-python 9.1, on linux fedora 10, 64 bits

Please provide any additional information below.

Changing 'attrname' in the program from "_FillValue" to something else solves 
the problem... Is there something wrong with this attribute name ?

Thanks,
Martin
```

Original issue reported on code.google.com by `martin.r...@gmail.com` on 22 Jun 2010 at 10:37

Attachments:
- [testcase.py](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-54/comment-0/testcase.py)

**Comment by GoogleCodeExporter** [comment]
```
What version of the HDF5 library are you linking?  

(can't reproduce this error here on macos x 10.5  using 1.8.4-patch1, but I 
will try on a x86_64 linux system tomorrow)
```

Original comment by `whitaker.jeffrey@gmail.com` on 22 Jun 2010 at 11:26

**Comment by GoogleCodeExporter** [comment]
```
HDF5 version is 1.8.5, and netcdf is 4.1.1

Thanks for the quick reaction :)

Martin
```

Original comment by `martin.r...@gmail.com` on 22 Jun 2010 at 11:42

**Comment by GoogleCodeExporter** [comment]
```
This error happens with hdf5 1.8.5, but not 1.8.4-patch1.  No idea why.

However, it's probably not a good idea to set the _FillValue this way.  
_FillValue is a special netcdf attribute that controls how the variable is 
filled when the varable is created and before any data is written to it. 
Therefore, it's best to set it when the variable is created, before anything 
else has happend to it.  You can set it at variable creation time using the 
fill_value keyword to createVariable, i.e. in your example

var_a = rootgrp.createVariable("A", 'float64', ('x', 'y'),fill_value=-99999.)

This seems to work fine in both versions of hdf5.

I still consider this a bug though - probably in the hdf5 library or the 
netcdf-4 C libraries.  I'll try to write a simple C program that triggers it 
and then report it to unidata.
```

Original comment by `whitaker.jeffrey@gmail.com` on 23 Jun 2010 at 11:40

**Comment by GoogleCodeExporter** [comment]
```
It also works with hdf5 1.8.5 if you set the attribute right after the variable 
is created, before you do anything else to the file, i.e.

attrname = "_FillValue"
var_a = rootgrp.createVariable("A", 'float64', ('x', 'y'))
setattr(var_a, attrname, np.float64(-99999.))
var_b = rootgrp.createVariable("B", 'float64', ('x', 'y'))
setattr(var_b, attrname, np.float64(-99999.))

```

Original comment by `whitaker.jeffrey@gmail.com` on 23 Jun 2010 at 11:57

**Comment by GoogleCodeExporter** [comment]
```
Indeed, it does work the way you describe it.

Thank you very much for the help !

Martin
```

Original comment by `martin.r...@gmail.com` on 23 Jun 2010 at 6:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
