### ISSUE TITLE
Test tst_dap.py fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#61]
```
What steps will reproduce the problem?
1. Compile and install
2. cd test
3. python tst_dap.py

What is the expected output? What do you see instead?
python tst_dap.py
E
======================================================================
ERROR: testing access of data over http using opendap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst_dap.py.bak", line 28, in runTest
    file = netCDF4.Dataset(URL)
  File "netCDF4.pyx", line 1324, in netCDF4.Dataset.__init__ (netCDF4.c:5860)
RuntimeError: No such file or directory

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)

What version of the product are you using? On what operating system?
0.9.1 on ArchLinux (netcdf 4.1.1-2 and hdf5 1.8.4_patch1-1)


```

Original issue reported on code.google.com by `nbigaoue...@gmail.com` on 21 Jul 2010 at 9:28

**Comment by GoogleCodeExporter** [comment]
```
Did you build the netcdf library with --enable-dap?


```

Original comment by `whitaker.jeffrey@gmail.com` on 21 Jul 2010 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
It looks like the ArchLinux netcdf package does not enable dap in the netcdf 
library.  So, unless you build netcdf yourself, you won't get dap support in 
the python module.
```

Original comment by `whitaker.jeffrey@gmail.com` on 21 Jul 2010 at 10:47

**Comment by GoogleCodeExporter** [comment]
```
Ok thanx. I guess it can be closed ;)
```

Original comment by `nbigaoue...@gmail.com` on 21 Jul 2010 at 10:49

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 21 Jul 2010 at 11:04
- Changed state: **Invalid**
