### ISSUE TITLE
Problem with group creation/deletion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#65]
```
Hi,

I have a problem with group creation/deletion. In fact, I would like to create 
a new group (new variables...) but using an existing name, that is to say I 
want to erase an old group by a newer, using the same name.

First, I create the group 'test' :

>>> import netCDF4
>>> rootGrp = netCDF4.Dataset("test.nc", 'w', format='NETCDF4')
>>> rootGrp.groups
OrderedDict()
>>> rootGrp.createGroup('test')
<netCDF4.Group object at 0x1bd1bf0>
>>> rootGrp.groups
OrderedDict([('test', <netCDF4.Group object at 0x1bd1bf0>)])

Then, I delete this group :

>>> del rootGrp.groups['test']
>>> rootGrp.groups
OrderedDict()

Now, I would like to create the new :

>>> rootGrp.createGroup('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "netCDF4.pyx", line 1619, in netCDF4.Dataset.createGroup (netCDF4.c:7714)
  File "netCDF4.pyx", line 1741, in netCDF4.Group.__init__ (netCDF4.c:8835)
RuntimeError: NetCDF: String match to name in use

Is it a bug or I don't use the good way to remove a group ?

Versions :
python 2.5.4
numpy 1.3.0
netCDF4 0.9.2
hdf5 1.8.5
netcdf 4.1.1

Thanks

Martin
```

Original issue reported on code.google.com by `chowy.th...@gmail.com` on 7 Sep 2010 at 3:00

**Comment by GoogleCodeExporter** [comment]
```
Martin:  You just deleted the reference to the group in the python dictionary 
that that netcdf4-python uses to keep track of the groups.  That doesn't 
eliminate the group in the file.  In fact, it doesn't look like it is possible 
to delete groups, variables or dimensions from netcdf files once they are 
created.  I'll check with the unidata folks to make sure though.
```

Original comment by `whitaker.jeffrey@gmail.com` on 7 Sep 2010 at 3:11

**Comment by GoogleCodeExporter** [comment]
```
Martin: It turns out that this is an issue with the underlying hdf5 library.  
It is possible to delete objects from HDF5 files, but this doesn't free the 
space from the file.  It's as if the object is still there, but just not 
visible to the user.  To reclaim the space, you actually have to rewrite the 
file, leaving out the undesired variables, dimensions and/or groups.
```

Original comment by `whitaker.jeffrey@gmail.com` on 7 Sep 2010 at 3:23

**Comment by GoogleCodeExporter** [comment]
```
Ok. Thank you very much...
```

Original comment by `chowy.th...@gmail.com` on 7 Sep 2010 at 3:31

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
