### ISSUE TITLE
RuntimeError: Bad chunk sizes.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#66]
```
What steps will reproduce the problem?
1. creating a netCDF4 variable with zlib compression AND chunksizes
2. more than 1 dimension (see attached file)
3. was working correctly on Python 2.6 32bit with HDF5-1.8.4

What is the expected output? What do you see instead?

======================================================================
ERROR: runTest (__main__.CompressionTestCase)
testing zlib and shuffle compression filters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst_compression.py", line 51, in setUp
    write_netcdf2(self.files[7],True,None,array,shuffle=True,chunksizes=(10,ndim2))
  File "tst_compression.py", line 26, in write_netcdf2
    foo = file.createVariable('data', dtype,('n', 'n2'),zlib=zlib,least_significant_digit=least_significant_digit,shuffle=shuffle,contiguous=contiguous,complevel=complevel,fletcher32=fletcher32,chunksizes=chunksizes)
  File "netCDF4.pyx", line 1584, in netCDF4.Dataset.createVariable (netCDF4.c:7310)
  File "netCDF4.pyx", line 2121, in netCDF4.Variable.__init__ (netCDF4.c:11550)
RuntimeError: Bad chunk sizes.

What version of the product are you using? On what operating system?

MacOS 10.6, HDF5-1.8.5-patch1, netcdf-4.1.1, netCDF-0.9.2, Python 2.7 64 bit

Please provide any additional information below.

The chunksizes option in createVariable seems not to be tested.
```

Original issue reported on code.google.com by `mi...@webheld.de` on 17 Sep 2010 at 5:10

Attachments:
- [tst_compression.py](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-66/comment-0/tst_compression.py)

**Comment by GoogleCodeExporter** [comment]
```
I just checked the same test-code on a 64bit linux running Python 2.6.6, 
hdf5-1.8.4-patch1, netcdf-4.1.1, and netCDF 0.9.1 and the same error occurs. so 
I guess this can be traced down to a 64bit issue...?!
```

Original comment by `mi...@webheld.de` on 17 Sep 2010 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
I got the 32bit version with Python 2.6.6 up and running again. No errors. I 
made a mistake in the test case which is newly attached.
Now I get a different error for when running the 64bit Python 2.7:

ERROR: runTest (tst_compression.CompressionTestCase)
testing zlib and shuffle compression filters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/miheld/Downloads/netCDF4-0.9.2/test/tst_compression.py", line 52, in setUp
    write_netcdf2(self.files[7],True,None,array2,shuffle=True,chunksizes=(10,ndim2))
  File "/Users/miheld/Downloads/netCDF4-0.9.2/test/tst_compression.py", line 28, in write_netcdf2
    foo[:] = data
  File "netCDF4.pyx", line 2641, in netCDF4.Variable.__setitem__ (netCDF4.c:18030)
  File "netCDF4.pyx", line 2765, in netCDF4.Variable._put (netCDF4.c:19018)
RuntimeError: HDF error

```

Original comment by `mi...@webheld.de` on 17 Sep 2010 at 7:05

Attachments:
- [tst_compression.py](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-66/comment-2/tst_compression.py)

**Comment by GoogleCodeExporter** [comment]
```
the full report:

...HDF5-DIAG: Error detected in HDF5 (1.8.4-patch1) thread 0:
  #000: H5Pdcpl.c line 969 in H5Pset_chunk(): all chunk dimensions must be less than 2^32
    major: Invalid arguments to routine
    minor: Out of range
E...................................
======================================================================
ERROR: runTest (tst_compression.CompressionTestCase)
testing zlib and shuffle compression filters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/miheld/Downloads/netCDF4-0.9.2/test/tst_compression.py", line 52, in setUp
    write_netcdf2(self.files[7],True,None,array2,shuffle=True,chunksizes=(10,ndim2))
  File "/Users/miheld/Downloads/netCDF4-0.9.2/test/tst_compression.py", line 28, in write_netcdf2
    foo[:] = data
  File "netCDF4.pyx", line 2641, in netCDF4.Variable.__setitem__ (netCDF4.c:18030)
  File "netCDF4.pyx", line 2765, in netCDF4.Variable._put (netCDF4.c:19018)
RuntimeError: HDF error
```

Original comment by `mi...@webheld.de` on 17 Sep 2010 at 7:06

**Comment by GoogleCodeExporter** [comment]
```
and the same result for HDF5-1.8.5-patch1

...HDF5-DIAG: Error detected in HDF5 (1.8.5-patch1) thread 0:
  #000: H5Pdcpl.c line 860 in H5Pset_chunk(): all chunk dimensions must be less than 2^32
    major: Invalid arguments to routine
    minor: Out of range
E...................................
======================================================================
ERROR: runTest (tst_compression.CompressionTestCase)
testing zlib and shuffle compression filters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/miheld/Downloads/netCDF4-0.9.2/test/tst_compression.py", line 52, in setUp
    write_netcdf2(self.files[7],True,None,array2,shuffle=True,chunksizes=(10,ndim2))
  File "/Users/miheld/Downloads/netCDF4-0.9.2/test/tst_compression.py", line 28, in write_netcdf2
    foo[:] = data
  File "netCDF4.pyx", line 2641, in netCDF4.Variable.__setitem__ (netCDF4.c:18030)
  File "netCDF4.pyx", line 2765, in netCDF4.Variable._put (netCDF4.c:19018)
RuntimeError: HDF error
```

Original comment by `mi...@webheld.de` on 17 Sep 2010 at 7:39

**Comment by GoogleCodeExporter** [comment]
```
What version of the netcdf library are you using with hdf5-1.8.5-patch1?

Do all the tests pass?  (cd test; python run_all.py)

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 18 Sep 2010 at 3:17

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I missed that you already stated your netcdf version was 4.1.1

I think what you are seeing is a known bug in 4.1.1.  I just tried with the 
latest netcdf svn from 

http://svn.unidata.ucar.edu/repos/netcdf/trunk

with hdf5-1.8.5-patch1, and your test script worked (with 32 bit python 2.6.6 
on macosx 10.5).  There is a netcdf-4.1.2-beta1 available from 
ftp.unidata.ucar.edu/pub/netcdf, that may work for you also (it doesn't for me 
though since it won't build on macos x 10.5).

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 18 Sep 2010 at 3:26

**Comment by GoogleCodeExporter** [comment]
```
Hey Jeff,

I am not sure if that was clear, but the test script I attached worked also for 
me on a 32bit Python 2.6.6 on MacOS 10.6. 
thanks for the hint to look for netcdf-4.1.2-beta1. they also seem to have a 
beta2 in preparation, but the links are not working right now.
I got netcdf-4.1.2-beta1 compiled on my MacOS 10.6, but I had to disable dap 
for some reason. make check worked fine. the configure looks like

./configure --with-hdf5=/Users/miheld/cecog_dependencies_universal/ 
--with-zlib=/usr  --prefix=/Users/miheld/cecog_dependencies_universal/ 
--enable-shared --enable-netcdf-4 --disable-f77 --disable-f90 --disable-dap

running python2.6 run_all.py shows a lot of errors this time, most of all show 
the message below. I have attached to full list.

thanks for your efforts you are putting into this library. I can imagine it's 
hard sometimes...
cheers
michael


EEEFEEE..E.........EEEE.EE...........EE
======================================================================
ERROR: testing attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/miheld/Downloads/netCDF4-0.9.2/test/tst_atts.py", line 44, in setUp
    g = f.createGroup(GROUP_NAME)
  File "netCDF4.pyx", line 1619, in netCDF4.Dataset.createGroup (netCDF4.c:7714)
  File "netCDF4.pyx", line 1741, in netCDF4.Group.__init__ (netCDF4.c:8835)
RuntimeError: NetCDF: Attempting netcdf-4 operation on netcdf-3 file

```

Original comment by `mi...@webheld.de` on 18 Sep 2010 at 9:19

Attachments:
- [run_all_result.txt](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-66/comment-7/run_all_result.txt)

**Comment by GoogleCodeExporter** [comment]
```
Yes, I get that error too with 4.1.2-beta1.  Works fine with svn though - so 
you'll either have to wait for the release of beta2 or checkout for svn.

If you do checkout from svn, you'll need to run

autoreconf -f -i -Wall,no-obsolete

in the source directory to generate the configure script.

It's definitely a library problem that occurs with certain combinations of 
netcdf-4 and hdf5, so it's not something I can fix in the python extension.  
Hopefully we'll get a stable combination of released versions of netcdf-4 and 
hdf5 soon.


-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 18 Sep 2010 at 9:46

**Comment by GoogleCodeExporter** [comment]
```
Hey Jeff,

Are you referring the SVN version of netcdf or python-netcdf? The first I could 
not find online, and python-netcdf svn rev909 causes kind of the same problems 
as described above for netcdf-4.1.2-beta1

Cheers
Michael  
```

Original comment by `mi...@webheld.de` on 19 Sep 2010 at 4:23

**Comment by GoogleCodeExporter** [comment]
```
I'm referring to netcdf. Sorry, I forgot to give you the URL

svn co http://svn.unidata.ucar.edu/repos/netcdf/trunk netcdf

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 19 Sep 2010 at 6:35

**Comment by GoogleCodeExporter** [comment]
```
Hey Jeff,

so I am running the latest netcdf and python-netcdf from SVN. the now build-in 
DAP support does not compile for me. 
32bit Python 2.6.6 works fine with my test, 64bit Python 2.7 gives the same 
error. I wonder when this is a netcdf bug if anybody is noticing there. 
for the 4.1.2-beta1 version I had some strange error where the chunksize was 
regarded as >2^32 appearing from the HDF5 engine. that vanished.

E
======================================================================
ERROR: runTest (__main__.CompressionTestCase)
testing zlib and shuffle compression filters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tst_compression2.py", line 52, in setUp
    write_netcdf2(self.files[7],True,None,array2,shuffle=True,chunksizes=(10,ndim2))
  File "tst_compression2.py", line 27, in write_netcdf2
    foo = file.createVariable('data', dtype,('n', 'n2'),zlib=zlib,least_significant_digit=least_significant_digit,shuffle=shuffle,contiguous=contiguous,complevel=complevel,fletcher32=fletcher32,chunksizes=chunksizes)
  File "netCDF4.pyx", line 1584, in netCDF4.Dataset.createVariable (netCDF4.c:7755)
  File "netCDF4.pyx", line 2121, in netCDF4.Variable.__init__ (netCDF4.c:12455)
RuntimeError: NetCDF: Bad chunk sizes.

----------------------------------------------------------------------
Ran 1 test in 0.312s


Cheers
Michael
```

Original comment by `mi...@webheld.de` on 20 Sep 2010 at 10:22

**Comment by GoogleCodeExporter** [comment]
```
what version of numpy are you using with python 2.7?
```

Original comment by `whitaker.jeffrey@gmail.com` on 20 Sep 2010 at 12:28

**Comment by GoogleCodeExporter** [comment]
```
I was able to reproduce your error with 64-bit python 2.6.6 with hdf5 
1.8.5-patch1 and netcdf 4.1.2-beta1 on macos 10.6.  All the tests pass, but 
your test script gives that "Bad chunk sizes" error.  I will investigate 
further and let you know what I find.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 20 Sep 2010 at 3:10

**Comment by GoogleCodeExporter** [comment]
```
OK, I found it.  It was a bug in the netcdf4-python module.  I was treating the 
chunksizes variable as int, but it should be size_t.  Fixed now. Can you update 
from svn and confirm?

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 20 Sep 2010 at 7:16

**Comment by GoogleCodeExporter** [comment]
```
Hey Jeff,

thanks for your fix! That works pretty well. Problem solved! :-)

The integrated DAP support is still not compiling. Do you see any solution for 
that on the netcdf side?

Cheers
Michael
```

Original comment by `mi...@webheld.de` on 20 Sep 2010 at 11:28

**Comment by GoogleCodeExporter** [comment]
```
I've never had any problem with the dap support.  What's the compilation error 
look like?


```

Original comment by `whitaker.jeffrey@gmail.com` on 21 Sep 2010 at 12:52

**Comment by GoogleCodeExporter** [comment]
```
Enabling DAP on my MacOS 10.6 works now and all tests including the chunk-size 
test run trough.

I had to install netCDF on a RHEL 5.5 system, and there are many errors when 
using the beta1. The svn version (rev 445) needed some tweaks since autoreconf 
would exit with a macro error (AC_TYPE_LONG_LONG_INT not found).
I managed to hack the configure.ac and configure files and needed to disable 
DAP (see error below), but got it up and running. All Python tests despite the 
DAP run trough.
This is really a pain! How can I convince my colleagues to use netCDF? Or 
should I switch back to HDF5?

Cheers
Michael

Error message (fixed by disabling DAP):
./configure --with-hdf5=/home/miheld/ --with-zlib=/usr 
--with-szlib=/home/miheld/ --prefix=/home/miheld/ --enable-shared 
--enable-netcdf-4 --disable-f77 --disable-f90 --disable-fortran-type-check
[...]
checking what to call the output of the ftpbin target... 
binary-netcdf-4.1.2-beta2_c++.tar gfortran c++
checking binary distribution directory... /home/ftp/pub/binary/dummy_system
checking for library containing xdr_void... none required
configure: error: Cannot locate library containing xdr functions.

```

Original comment by `mi...@webheld.de` on 27 Sep 2010 at 2:09

**Comment by GoogleCodeExporter** [comment]
```
I agree it is a pain.  I'm hoping the unidata folks will work out the bugs 
before 4.1.2 final.  I would suggest emailing unidata support 
(support-netcdf@unidata.ucar.edu) to let them know about that dap error.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 27 Sep 2010 at 3:43

**Comment by GoogleCodeExporter** [comment]
```
I just built netCDF4-0.9.3 against netcdf-4.1.2 on 64-bit Windows and I, too, 
am getting lots of these errors:

RuntimeError: NetCDF: Attempting netcdf-4 operation on netcdf-3 file

I attached a file with the first few errors.  I've now built several different 
4.1.1 and 4.1.2 versions and I get these errors everytime.  Is this a definite 
problem with the NetCDF package ?  I see that there is a 4.1.3 version out now, 
but I'm hesitant to build yet another version since there is a lot of tweaking 
involved to get it to build right with MSVC.

```

Original comment by `kriswe...@gmail.com` on 15 Jun 2011 at 8:57

Attachments:
- [netcdf4tests.txt](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-66/comment-19/netcdf4tests.txt)

**Comment by GoogleCodeExporter** [comment]
```
All the tests pass for me on macos x.   I don't know if it's a generic windows 
only issue, or an issue with your build.  I haven't had any other problem 
reports from Windows users though.  There are 64-bit windows installers for 
netcdf4-python and netcdf-4.1.2 at http://www.lfd.uci.edu/~gohlke/pythonlibs,  
perhaps you could try those?
```

Original comment by `whitaker.jeffrey@gmail.com` on 16 Jun 2011 at 7:10

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the link.  I built netcdf-4.1.2 from the source on that site, then I 
built/installed netcdf-python 0.9.4.  When I run "python run_all.py" in the 
"test" directory, I still get those errors.  I have attached the complete 
output from the tests.  I've tried many different things now and I always get 
these errors.  Can you provide some insight into what those errors messages 
mean ?  I'm specifically interested in the "Attempting netcdf-4 operation on 
netcdf-3 file" messages since those are the most prominent.  Thanks.
```

Original comment by `kriswe...@gmail.com` on 16 Jun 2011 at 1:39

Attachments:
- [output.txt](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-66/comment-21/output.txt)

**Comment by GoogleCodeExporter** [comment]
```
I've never seen that error before.  Can you try installing one of Christoph's 
binary installers for netcdf4-python 0.9.4 and see if youi still get that error?

Are you sure you built netcdf-4.1.2 with netcdf-4 support (using 
--enable-netcdf-4).  You would of course also have to have HDF5 in that case.
```

Original comment by `whitaker.jeffrey@gmail.com` on 16 Jun 2011 at 1:42

**Comment by GoogleCodeExporter** [comment]
```
OK, I had made a mistake in my previous test.  The test run was still picking 
up an old DLL.  I fixed the issue and now those "Attempting netcdf-4 operation 
on netcdf-3 file" errors are gone.  However, I'm left with some other errors.  
I have attached the output.  Interestingly, the Enthought Python package throws 
almost these exact same errors when running the unit tests.
```

Original comment by `kriswe...@gmail.com` on 16 Jun 2011 at 2:26

Attachments:
- [output.txt](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-66/comment-23/output.txt)

**Comment by GoogleCodeExporter** [comment]
```
BTW, here are the errors when I run those tests with Enthought Python.  They 
are nearly identical.  Enthought uses netcdf-4.1.1 and I used 4.1.2, so that 
may explain the extra failure on their distribution.  Still, now that I'm 
seeing these test failures on their official release, I'm leaning towards just 
releasing what I have built.  Any thoughts on this ?


```

Original comment by `kriswe...@gmail.com` on 16 Jun 2011 at 2:29

Attachments:
- [output_epd.txt](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-66/comment-24/output_epd.txt)

**Comment by GoogleCodeExporter** [comment]
```
Fixed output file
```

Original comment by `kriswe...@gmail.com` on 16 Jun 2011 at 2:40

Attachments:
- [output_epd.txt](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-66/comment-25/output_epd.txt)

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
