### ISSUE TITLE
segfault when including a condition in an opendap url

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#71]
```
What steps will reproduce the problem?
1. Run the attached file.
2.
3.

What is the expected output? What do you see instead?

efiring@manini:~$ python ncsegfault.py
0.9.3
Segmentation fault


What version of the product are you using? On what operating system?

0.9.3 on Ubuntu 10.10, 64-bit
hdf5-1.8.4-patch1
netcdf-4.1.1


Please provide any additional information below.

The url causing trouble accesses the ARGO data set, which is in a style of 
netcdf I have never dealt with before.  There is a max transfer limit that 
seems to make it impossible to use netCDF4 without putting conditions in the 
url to limit the array size; otherwise, I can't figure out how to access 
anything beyond the 15000th profile.  I tried pydap, which even uses ARGO as an 
example in the docs, but ran into trouble there also--it seemed to vary between 
unusably slow and hung, with no activity.

```

Original issue reported on code.google.com by `efiring....@gmail.com` on 30 Oct 2010 at 7:18

Attachments:
- [ncsegfault.py](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-71/comment-0/ncsegfault.py)

**Comment by GoogleCodeExporter** [comment]
```
Eric - I'm able to run that script without a segfault using hdf5-1.8.5patch1 
and svn netcdf (http://svn.unidata.ucar.edu/repos/netcdf/trunk/).  Haven't 
tried to access any data yet.

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 13 Nov 2010 at 7:08

**Comment by GoogleCodeExporter** [comment]
```
There seems to be no data in the file (unlimited dimension size is 0).  Very 
strange.

ncdump -h http://dapper.pmel.noaa.gov/dapper/argo/argo_all.cdp
netcdf argo_all {
dimensions:
        unlimited = UNLIMITED ; // (0 currently)
        constrained_ranges.depth_range_0 = 2 ;
        constrained_ranges.lat_range_0 = 2 ;
        constrained_ranges.lon_range_0 = 2 ;
        constrained_ranges.time_range_0 = 2 ;
        location = 15000 ;
        location.variable_attributes.PRES.valid_range_1 = 2 ;
        maxStrlen64 = 64 ;
variables:

```

Original comment by `whitaker.jeffrey@gmail.com` on 13 Nov 2010 at 9:08

**Comment by GoogleCodeExporter** [comment]
```
Jeff,
I don't know how to interpret the unlimited dimension, but the location 
dimension reflects the download limit placed on the file.  Without constraining 
the URL one can access the first 15000 profiles, but that's all.  (pydap seems 
to have another mechanism for setting constraints, but as I originally noted, I 
could not get it to work.)
I checked out the svn version of netcdf, but I have not yet succeeded in 
building it. I ran autoconf, with complaints about some symbols; but when I try 
to run configure, it fails with 

efiring@manini:~/programs/netcdf_svn$ ./configure --enable-netcdf-4 
--with-hdf5=/usr/local     --with-zlib=/usr --enable-shared --prefix=/usr/local 
     --enable-dap
configure: netCDF 4.1.2-beta2
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." 
"./../.."

True, they are not there--but I have no idea how they are supposed to get 
there.  Are there instructions somewhere for building from svn?

Eric

```

Original comment by `efiring....@gmail.com` on 14 Nov 2010 at 12:01

**Comment by GoogleCodeExporter** [comment]
```
Eric:  Here's what I do with a fresh netcdf checkout

autoreconf -f -i -Wall,no-obsolete

then

./configure --prefix=/Users/jsw --enable-netcdf-4 --enable-shared --enable-dap 
--with-hdf5=/Users/jsw

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 17 Nov 2010 at 1:15

**Comment by GoogleCodeExporter** [comment]
```
Jeff,

Thanks, that got me past the netcdf svn compilation barrier.  I also updated 
hdf5 to the version you cite above.  No joy.  My test script is still 
segfaulting.

It turns out that nc_open is rejecting the url--either I haven't written it 
correctly, or it can't handle constraints in the url.  In any case, the next 
problem is that running nc_strerror(ierr) yields something that cython can't 
seem to handle--can't make it printable, or treatable as a string, no matter 
what I try.  Based on the cython docs, it appeared that the decode method 
should do the trick, but that doesn't work.

Modifying the Dataset.__init__ method for debugging:

        print "about to check ierr"
        print "ierr is %s, will be compared to %s" %(str(ierr), str(NC_NOERR))
        if ierr != NC_NOERR:
            print "about to evaluate nc_strerror(ierr)"
            temp_error = nc_strerror(ierr)
            print "assigned to temp_error"
            te = temp_error.decode('UTF-8')
            print "ran decode method"
            print te
            print "tried to print decoded error message"
            print str(temp_error.decode('UTF-8'))
            print "ready to raise RuntimeError"
            raise RuntimeError(nc_strerror(ierr))
        # file format attribute.
        print "about to get format"
        self.file_format = _get_format(grpid)
        print self.file_format

yields

about to check ierr
ierr is 1, will be compared to 0
about to evaluate nc_strerror(ierr)
assigned to temp_error
ran decode method
Operation not permitted
tried to print decoded error message
Operation not permitted
ready to raise RuntimeError
Segmentation fault

(In the debugging version I also included cdef char * temp_error.)

I'm stumped--but if it is correct that netcdf dap support does not handle 
constraints in the url, then the issue at this point is one of error handling, 
and how to get the error message into a string argument that RuntimeError() is 
happy with.

I have no idea why this problem appears on my system and not on yours.

The problem originally appeared with the C files from your cythonizing, which I 
think was done with a recent cython, and persists after I updated cython from 
the hg repo.

Eric




```

Original comment by `efiring....@gmail.com` on 18 Nov 2010 at 1:23

**Comment by GoogleCodeExporter** [comment]
```
Update: I was wrong, and "Operation not permitted" is the thoroughly 
uninformative error message from nc_open via nc_strerror.  (I was interpreting 
it as a cython error message.)  The segfault occurs when RuntimeError is 
raised, regardless of its argument, so it seems to be a case of a faulty 
shutdown procedure within netcdf itself, or resulting from the code generated 
by cython.
```

Original comment by `efiring....@gmail.com` on 18 Nov 2010 at 2:16

**Comment by GoogleCodeExporter** [comment]
```
Now I'm getting segfaults too (it worked before).  Strange.  I'm going on 
vacation for a week, but I'll look into this more when I get back.

```

Original comment by `whitaker.jeffrey@gmail.com` on 18 Nov 2010 at 2:32

**Comment by GoogleCodeExporter** [comment]
```
reported to Unidata.  Will post any replies I get here.
```

Original comment by `whitaker.jeffrey@gmail.com` on 26 Nov 2010 at 2:12

**Comment by GoogleCodeExporter** [comment]
```
Eric:  With the latest netcdf svn, your test script no longer segfaults but 
gives

Traceback (most recent call last):
  File "/Users/jwhitaker/Downloads/ncsegfault.py", line 8, in <module>
    d2 = Dataset(urlbase + urlsel, 'r')
  File "netCDF4.pyx", line 1328, in netCDF4.Dataset.__init__ (netCDF4.c:6336)
    raise RuntimeError(nc_strerror(ierr))

If I change the constraint to

urlsel = '?&location.LATITUDE<1&location.LATITUDE>-1'

(adding the ampersand after the first ?)

it actually works.  So, it looks like a bug in the lib was causing a segfault 
on an invalid constraint.  

-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 29 Nov 2010 at 8:47

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
