### ISSUE TITLE
Errors setting attributes when subclassing Dataset class

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#87]
```
What steps will reproduce the problem?

Run the attached script. It does the following:

 1. Create a python wrapper class WDataset inheriting from netCDF4.Dataset
 2. Define two methods which use a) netCDF4.Dataset and b) WDataset to create a netcdf file for writing and setting a global 'title' attribute
 3. Run the two functions

What is the expected output? What do you see instead?

Expected: Two netcdf files with properly set 'title' attributes.

Instead: The netcdf file created with netCDF4.Dataset works fine, but the for 
the file created an AttributeError is thrown. The output of running the test 
script is:

   > python test_netcdf.py
   Running normal class test
   Running wrapped class test
   Traceback (most recent call last):
     File "test_netcdf.py", line 32, in <module>
       test_wrapped()
     File "test_netcdf.py", line 19, in test_wrapped
       nc.title = "A wrapped title"
     File "netCDF4.pyx", line 1706, in netCDF4.Dataset.__setattr__ (netCDF4.c:15621)
     File "netCDF4.pyx", line 1665, in netCDF4.Dataset.setncattr (netCDF4.c:15217)
     File "netCDF4.pyx", line 1022, in netCDF4._set_att (netCDF4.c:10256)
   AttributeError: NetCDF: Name contains illegal characters


What version of the product are you using? On what operating system?

netCDF4 0.9.4; cython 0.14.1; python 2.7.1; numpy 1.5.1; netcdf 4.1.2; HDF 
1.8.6, all compiled with Intel Fortran and C/C++ compilers 11.1


Please provide any additional information below.

The attached patch fixes the issue for me, but I don't understand why calling 
the same _set_att() method once directly through the orginal C extension class 
works fine, but doesn't work if called through the python wrapping. BTW, the 
wrapped class contains one additional method (which represents my use case for 
the wrapping), but the test also fails without having that class defined or 
being used..

For completeness: The output of the successful run is

   > python test_netcdf.py
   Running normal class test
   Running wrapped class test
      Some test string to be printed...
   Done


```

Original issue reported on code.google.com by `Marquard...@gmail.com` on 12 May 2011 at 9:03

Attachments:
- [test_netcdf.py](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-87/comment-0/test_netcdf.py)
- [netCDF4-0.9.4._set_att.patch](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-87/comment-0/netCDF4-0.9.4._set_att.patch)

**Comment by GoogleCodeExporter** [comment]
```
Oops - of course I forgot - the OS is Linux OpenSuse 11.1.
```

Original comment by `Marquard...@gmail.com` on 12 May 2011 at 11:21

**Comment by GoogleCodeExporter** [comment]
```
That's very weird.  Unfortunately, your fix will break python 3.  No idea 
what's going on yet, still investigating ...
```

Original comment by `whitaker.jeffrey@gmail.com` on 14 May 2011 at 6:52

**Comment by GoogleCodeExporter** [comment]
```
I've committed a workaround (skip the conversion to bytes for python 2).
```

Original comment by `whitaker.jeffrey@gmail.com` on 15 May 2011 at 2:15

**Comment by GoogleCodeExporter** [comment]
```
I'm experimenting the same error with the last revision installed (r1029) and 
Python v3.2

```

Original comment by `pedr...@gmail.com` on 18 May 2011 at 11:44

**Comment by GoogleCodeExporter** [comment]
```
I don't see the error with python 2.7.1 or python 3.2 with revision 1029.  Are 
you sure you are actually getting the updated version in python 3.2?


```

Original comment by `whitaker.jeffrey@gmail.com` on 18 May 2011 at 12:22

**Comment by GoogleCodeExporter** [comment]
```
Yes...

I've done another test. The file uploaded by Marquard...@gmail.com run 
correctly in my machine, but if I try the following code, I get an error 
message just when the attribute name has more than 7 characters:

###

import netCDF4

class NetCDF(netCDF4.Dataset):
    pass

f = NetCDF('test.nc', 'w')
f.title = 'Short title'
print('short title OK')
f.long_title = 'Long title'
print('long title OK')
f.close()
print('Done')

###


The output is:

short title OK
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    f.long_title = 'Long title'
  File "netCDF4.pyx", line 1708, in netCDF4.Dataset.__setattr__ (netCDF4.c:15541)
  File "netCDF4.pyx", line 1667, in netCDF4.Dataset.setncattr (netCDF4.c:15157)
  File "netCDF4.pyx", line 1024, in netCDF4._set_att (netCDF4.c:10248)
AttributeError: NetCDF: Name contains illegal characters


```

Original comment by `pedr...@gmail.com` on 18 May 2011 at 5:18

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I don't know what's wrong.  I can not reproduce this error with python 
3.2, 2.7.1 or 2.6.6.

What version of the netcdf and hdf5 libs are you using?
```

Original comment by `whitaker.jeffrey@gmail.com` on 18 May 2011 at 5:35

**Comment by GoogleCodeExporter** [comment]
```
I'm using netcdf 4.1.1 and hdf 1.8.4, from Synaptic (in ubuntu)

Thank you very much. Surely something is wrong in my computer.

Pedro

```

Original comment by `pedr...@gmail.com` on 18 May 2011 at 5:51

**Comment by GoogleCodeExporter** [comment]
```
I'm using hdf5 1.8.7 and netcdf 4.1.3-beta1,  All I can suggest is to upgrade 
to newer versions of the libs.
```

Original comment by `whitaker.jeffrey@gmail.com` on 18 May 2011 at 6:11

**Comment by GoogleCodeExporter** [comment]
```
Ok, thanks. I'll do it.

```

Original comment by `pedr...@gmail.com` on 18 May 2011 at 6:15

**Comment by GoogleCodeExporter** [comment]
```
Tested in a Mac (hdf5 1.8.7 and netcdf 4.1.1 from macports) and everything is 
OK.
Thank you for your patience.
Pedro

```

Original comment by `pedrogam...@gmail.com` on 20 May 2011 at 12:50

**Comment by GoogleCodeExporter** [comment]
```
(sorry, I'm pedr...@gmail.com)

```

Original comment by `pedrogam...@gmail.com` on 20 May 2011 at 12:51

**Comment by GoogleCodeExporter** [comment]
```
Hi, sorry to reactivate this old thread, but I'm having similar issues on an 
OpenSuse 11.3 (Python 2.6.5) machine with these netcdf related versions:
netcdf4-python version: 0.9.8
HDF5 lib version:       1.8.8
netcdf lib version:     4.1.3

A simple testcase as Pedr... ones gives the following error:
###
from netCDF4 import Dataset

class WrappedDataset(Dataset):
    pass

ds = Dataset('tests/testuncert.nc')
wrapds = WrappedDataset('tests/testuncert.nc')

print ds
print wrapds

ds.close()
wrapds.close()
###
<type 'netCDF4.Dataset'>
root group (NETCDF3_CLASSIC file format):
    Conventions: CF-1.4
    dimensions = ('lat', 'lon')
    variables = ('lat', 'lon', 'Min_temperature')
    groups = ()

Traceback (most recent call last):
  File "tests/simpleTest.py", line 10, in <module>
    print wrapds
  File "netCDF4.pyx", line 1350, in netCDF4.Dataset.__str__ (netCDF4.c:15298)
KeyError: u'Conventions'


```

Original comment by `mandsch...@googlemail.com` on 19 Apr 2012 at 9:24

**Comment by GoogleCodeExporter** [comment]
```
The example you give is not self-contained.  I assume test/testuncert.nc is an 
existing dataset.  You'll have to either include the file, or some code to 
create the file for us to run the script.  

Were you able to run the script in comment #6?
```

Original comment by `whitaker.jeffrey@gmail.com` on 19 Apr 2012 at 12:04

**Comment by GoogleCodeExporter** [comment]
```
True, sorry. The one I'm using there is ~1Mb size, didn't want to upload it. 
Anyway, I tried the example from #6, it worked, then used the created file with 
my example:

Output #6:
short title OK
long title OK
Done
Output 'test.nc' used in the example code:
<type 'netCDF4.Dataset'>
root group (NETCDF4 file format):
    title: Short title
    long_title: Long title
    dimensions = ()
    variables = ()
    groups = ()

Traceback (most recent call last):
  File "tests/simpleTest.py", line 10, in <module>
    print wrapds
  File "netCDF4.pyx", line 1350, in netCDF4.Dataset.__str__ (netCDF4.c:15298)
KeyError: u'title'
```

Original comment by `mandsch...@googlemail.com` on 19 Apr 2012 at 1:18

**Comment by GoogleCodeExporter** [comment]
```
Looks like the error occurs in the __repr__ method, it should go away if you 
don't try to print the wrapped Dataset object.  Can you confirm?
```

Original comment by `whitaker.jeffrey@gmail.com` on 19 Apr 2012 at 1:35

**Comment by GoogleCodeExporter** [comment]
```
Hmm, actually this is a stripped down version of a more complex example, where 
the print was the simplest to show the behavior. To me it looks as if the 
self.ncattrs() call can't access the attributes of the wrapped class object. 
```

Original comment by `mandsch...@googlemail.com` on 19 Apr 2012 at 1:48

**Comment by GoogleCodeExporter** [comment]
```
No, it was just a glitch in __unicode__ (trying to use self.__dict__ instead of 
self.getncattrs()).  I just updated svn with a fix - please give it a try and 
let me know how it goes.  
```

Original comment by `whitaker.jeffrey@gmail.com` on 19 Apr 2012 at 1:53

**Comment by GoogleCodeExporter** [comment]
```
Great, thanks. Due to our IT security i cannot easily update this, so it will 
take maybe until tomorrow :-|
But coming back to the more complex example I referred to: would this imply 
that the use of self.__dict__ is always a source of problems, in a scenario 
with classes that extend from Dataset? Because it's also used in __setattr__ 
and __getattr__.
```

Original comment by `mandsch...@googlemail.com` on 19 Apr 2012 at 3:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
