### ISSUE TITLE
UnicodeDecodeError when using MFDataset

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#92]
```
What steps will reproduce the problem?
1. Use .nc files (tested with NETCDF3_CLASSIC) that contain metadata with 
non-ascii values (I can provide some of these files if required)
2. Load the files using MFDataset(paths)

What is the expected output? What do you see instead?

Expected is an MFDataset object. The following is the traceback I receive 
instead:

Traceback (most recent call last):
  File "sg4e.py", line 627, in <module>
    main()
  File "sg4e.py", line 600, in main
    waves = WaveDataset(files, nodata)
  File "sg4e.py", line 307, in __init__
    self.ds = MFDataset(files)
  File "utils.pyx", line 253, in netCDF4.MFDataset.__init__ (netCDF4.c:2847)
  File "netCDF4.pyx", line 1725, in netCDF4.Dataset.__getattr__ (netCDF4.c:15787)
  File "netCDF4.pyx", line 938, in netCDF4._get_att (netCDF4.c:9073)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 2: ordinal 
not in range(128)

This does not happen when loading the files individually using the Dataset 
object.

What version of the product are you using? On what operating system?

I have tried 0.9.4 and 0.9.5, using numpy 1.5.1, netcdf4 4.1.2, hdf5 1.8.6 on 
an Arch Linux machine:
2.6.39-ARCH #1 SMP PREEMPT Mon Jun 27 22:01:13 CEST 2011 i686 Intel(R) 
Pentium(R) 4 CPU 2.80GHz GenuineIntel GNU/Linux

```

Original issue reported on code.google.com by `homme.zw...@gmail.com` on 7 Jul 2011 at 3:48

**Comment by GoogleCodeExporter** [comment]
```
Attached is one of the problem files using bzip2 compression. It can be tested 
with the following:

>>> netCDF4.MFDataset(['./SHOM_WW3-NORGAS-2MIN_20091101T00Z.nc'])

ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line statement', (2828, 0))

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
/home/homme/sg4e/waves/2009/<ipython console> in <module>()
/usr/lib/python2.7/site-packages/netCDF4.so in netCDF4.MFDataset.__init__ 
(netCDF4.c:2838)()
/usr/lib/python2.7/site-packages/netCDF4.so in netCDF4.Dataset.__getattr__ 
(netCDF4.c:15774)()
/usr/lib/python2.7/site-packages/netCDF4.so in netCDF4._get_att 
(netCDF4.c:9060)()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 2: ordinal 
not in range(128)
```

Original comment by `homme.zw...@gmail.com` on 7 Jul 2011 at 3:55

Attachments:
- [SHOM_WW3-NORGAS-2MIN_20091101T00Z.nc.bz2](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-92/comment-1/SHOM_WW3-NORGAS-2MIN_20091101T00Z.nc.bz2)

**Comment by GoogleCodeExporter** [comment]
```
I have just noticed that this issue is *not* present in version 0.9.3. I'm 
using Python 2.7.2 in all cases by the way.
```

Original comment by `homme.zw...@gmail.com` on 7 Jul 2011 at 4:18

**Comment by GoogleCodeExporter** [comment]
```
What is the encoding of the text attribute that causes the error? 
```

Original comment by `whitaker.jeffrey@gmail.com` on 9 Jul 2011 at 8:01

**Comment by GoogleCodeExporter** [comment]
```
netcdf4-python is treating strings are ascii by default.  Some of your 
attributes contain non-ascii values - but you can specify the encoding scheme 
to use if you don't want ascii.  For example, with your file this works:

import netCDF4
netCDF4.default_encoding = 'latin-1'
f = netCDF4.Dataset('SHOM_WW3-NORGAS-2MIN_20091101T00Z.nc')
print f.__dict__

Commenting out the second line, or replacing 'latin-1' with an 8-bit encoding 
like ascii or utf-8, triggers the traceback you reported.
```

Original comment by `whitaker.jeffrey@gmail.com` on 9 Jul 2011 at 8:52

**Comment by GoogleCodeExporter** [comment]
```
I've changed the default behavior in svn to replace characters that cannot be 
decoded with "?".  This behavior can be controlled by the "unicode_error" 
module variable, which is "replace" by default, but can also be set to "ignore" 
or "strict" (which was the prior behavior).  
```

Original comment by `whitaker.jeffrey@gmail.com` on 10 Jul 2011 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
Setting:

netCDF4.default_encoding = 'latin-1'

as per comment http://code.google.com/p/netcdf4-python/issues/detail?id=92#c4 
has solved the issue for me - thank you!


```

Original comment by `homme.zw...@gmail.com` on 13 Jul 2011 at 3:55

**Comment by GoogleCodeExporter** [comment]
```
Wouldn't the Windows-1252 encoding be a better default choice than latin-1 
(ISO-8859-1)? It has more printable characters.

"Windows-1252 differs from the IANA's ISO-8859-1 by using displayable 
characters rather than control characters in the 0x80 to 0x9F range" 
<http://en.wikipedia.org/wiki/Windows-1252>
```

Original comment by `cjgoh...@gmail.com` on 20 Jul 2011 at 6:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
