### ISSUE TITLE
Download opendap data with netcdf4-python

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#97]
```
Hi, this is not a problem with netcdf4-python, it is more like a question for a 
mailing list (but I could not find one so I'm sending it here.)

I made a quick-and-dirty hack to the nc3tonc4 script to take a dap url instead 
of a nc3 file. It works well for small data-sets, but it returns the following 
error for big data-sets:

Traceback (most recent call last):
  File "dap2file.py", line 274, in <module>
    quiet=quiet, classic=classic)
  File "dap2file.py", line 144, in dap2file
    idata = ncvar[:]
  File "netCDF4.pyx", line 2520, in netCDF4.Variable.__getitem__ (netCDF4.c:26502)
  File "netCDF4.pyx", line 2963, in netCDF4.Variable._get (netCDF4.c:31465)
MemoryError

The url I'm trying is this one:
url="http://tashtego.marine.rutgers.edu:8080/thredds/dodsC/cool/codar/totals/mac
oora6km"

Also, is it possible to get only the metadata for big data-sets? So the user 
can decided for a slice and only then get the data?

Thanks, Filipe.
```

Original issue reported on code.google.com by `ocefpaf` on 31 Aug 2011 at 7:51

Attachments:
- [dap2file.py](https://storage.googleapis.com/google-code-attachments/netcdf4-python/issue-97/comment-0/dap2file.py)

**Comment by GoogleCodeExporter** [comment]
```
Don't know - I suppose the arrays in that file are just too big to fit in 
memory (I can't open that URL from here).  You'll have to modify the code to 
read in those arrays in chunks.

With version 0.9.7, just do

nc = Dataset(URL)
print nc

to see the metadata.

You can also use the command line ncdump tool

ncdump -h URL


-Jeff
```

Original comment by `whitaker.jeffrey@gmail.com` on 31 Aug 2011 at 9:07

**Comment by GoogleCodeExporter** [comment]
```
Thanks, I'm using 0.9.7 (actually the latest svn source.)

I guess that the url above is so "heavy" that it made me think that netCDF4 was 
downloading all the data when I typed "nc = Dataset(URL)". However, a quick 
test with "ncdump -h" took the same amount of time.

I'm not an expert on opendap stuff, but I thought that downloading the url.dds 
or url.das would be "lighter". So I tried to get them with urllib and parse the 
result... but I guessed wrong, it also takes an eternity.

Thanks again, Filipe.
```

Original comment by `ocefpaf` on 1 Sep 2011 at 2:58

**Comment by GoogleCodeExporter** [comment]
```
Something is very wrong with that opendap server, it's probably dead.
```

Original comment by `whitaker.jeffrey@gmail.com` on 1 Sep 2011 at 3:06

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
