### ISSUE TITLE
Multifile-dataset on OpeNDAP cannot be opened

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sjaaky74/netcdf4-python#99]
```
Multi-file datasets can only be opened when they are available locally, not on 
OpeNDAP.

What steps will reproduce the problem:

Use for instance our Deltares OpeNDAP server to open the following dataset: 
'http://opendap.deltares.nl/thredds/dodsC/opendap/deltares/CRUERA40/*_CRUERA40.n
c'

This will give:

>>> a = 
MFDataset('http://opendap.deltares.nl/thredds/dodsC/opendap/deltares/CRUERA40/*_
CRUERA40.nc','r')
------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython console>", line 1, in <module>
  File "utils.pyx", line 243, in netCDF4.MFDataset.__init__ (netCDF4.c:2839)
ValueError: cannot using file globbing for remote (OPeNDAP) datasets

It would be very valuable if we could use MFDataset on remote servers as well. 
This should be possible since we have an implementation of multi-file datasets 
in our own software systems already (implemented in Java by the way).

Is it possible to include this option in future releases?

Kind regards
Hessel Winsemius
```

Original issue reported on code.google.com by `h.c.wins...@gmail.com` on 8 Sep 2011 at 7:04

**Comment by GoogleCodeExporter** [comment]
Original comment by `whitaker.jeffrey@gmail.com` on 26 Feb 2014 at 2:04
- Changed state: **Fixed**
